[Icon]
path = "\..\icons\pure-32.png"

[DefaultPage]
path = "\pages\index.html"

[PublicPages]
path = "\..\public"

[UserAllowedFileFormats]
formats[] = "application/json"
formats[] = "text/plain"
formats[] = "application/pdf"
formats[] = "image/gif"
formats[] = "image/jpeg"
formats[] = "image/png"